

import { Inter } from "next/font/google";
import "../globals.css";
import { redirect } from "next/navigation";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { getServerSession } from "next-auth";
import Image from "next/image";
import { headers } from "next/headers";
import AppSidebar from "../componentes/layout/AppSidebar";
import { Toaster } from "react-hot-toast";
import { Page } from "../models/Page";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import mongoose from "mongoose";
import { faEllipsis, faLink } from "@fortawesome/free-solid-svg-icons";
import Link from "next/link";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AppTemplate({ children, ...rest }) {
  const headersList = headers();
  const session = await getServerSession(authOptions);
  if (!session) {
    return redirect('/');
  }
  mongoose.connect(process.env.MONGODB_URI);
  const page = await Page.findOne({owner: session.user.email});
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
      <main className="md:flex min-h-screen">
          <label htmlFor="navCheckbox" className="shadow p-4 rounded-md inline-flex 
          items-center gap-2 cursor-pointer md:hidden ml-8 mt-4">
            <FontAwesomeIcon icon={faEllipsis} />
            <span>Abrir Navegação</span>
          </label>
          <input id="navCheckbox" type="checkbox" className="hidden"/>
          <label htmlFor="navCheckbox" className="hidden backdrop fixed inset-0 bg-black/80 z-10"></label>
        <aside className="bg-white w-48 p-4 pt-6 shadow fixed 
        md:static -left-48 top-0 bottom-0 z-20 transition-all">
            <div className="rounded-full overflow-hidden 
            aspect-square w-24 mx-auto">
              <Image src={session.user.image} width= {256}
              height={256} alt={'avatar'} />
            </div>
            {page && (
              <Link 
              target="_blank"
              href={'/' + page.uri}
              className="text-center mt-4 flex gap-1 items-center
              justify-center">
               <FontAwesomeIcon size="lg" icon={faLink} className="text-green-800" />
               <span className="text-xl text-gray-500">/</span> 
               <span>{page.uri}</span>
              </Link>
            )}
            <div className="text-center">
            <AppSidebar />  
          </div>
        </aside>
        <div className="grow">
            {children}
        </div>
      </main>
      </body>
    </html>
  );
}
